apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 5 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: mouadhn/myapp:v1 # Replace with your actual image name and tag
          ports:
            - containerPort: 3000 # Ensure this matches the targetPort of the service
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 3000 # Port the container is exposing
      nodePort: 30080 # Port on the node to access the service
  type: NodePort
